apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openstack-deploy-
  namespace: argo
spec:
  entrypoint: deploy
  serviceAccountName: argo-deploy-sa
  arguments:
    parameters:
    - name: app_name
      value: openstack
  templates:
  - name: deploy
    dag:
      tasks:
      - name: base
        templateRef:
          name: deploy-helmrelease
          template: ChartGroup
        arguments:
          parameters: 
          - name: chart_list
            value: |
              [
                "keystone",
                "glance",
                "cinder"
              ]
        dependencies: []
      - name: compute-kit 
        templateRef:
          name: deploy-helmrelease
          template: ChartGroup
        arguments:
          parameters: 
          - name: chart_list
            value: |
              [
                "libvirt",
                "nova",
                "neutron"
              ]
        dependencies: [base]
      - name: addon
        templateRef:
          name: deploy-helmrelease
          template: ChartGroup
        arguments:
          parameters: 
          - name: chart_list
            value: |
              [
                "horizon",
                "heat",
                "prometheus-openstack-exporter"
              ]
        dependencies: [base,compute-kit]
      - name: sona
        templateRef:
          name: deploy-helmrelease
          template: ChartGroup
        arguments:
          parameters: 
          - name: chart_list
            value: |
              [
                "sona"
              ]
        dependencies: [addon]
