apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: cleanup-helmreleases
spec:
  entrypoint: startpoint
  templates:
  - name: startpoint
    activeDeadlineSeconds: 180
    container:
      name: 'cleanup'
      image: k8s.gcr.io/hyperkube:v1.17.6
      command:
      - /bin/bash
      - -c
      - |
        function log() {
          level=$1
          msg=$2
          date=$(date '+%F %H:%M:%S')
          echo "[$date] $level     $msg"
        }

        list=$(kubectl get hr -ndefault -ojsonpath={.items[*].metadata.name})
        non_operator_charts=$(echo $list | sed 's/[a-z]*-operator//g')

        # delete non operator's HelmRelease
        log "INFO" "Deleting except operator charts: $non_operator_charts"
        kubectl delete hr $non_operator_charts -ndefault

        if [[ $? =~ 1 ]]; then
          log "WARNING" "kubectl delete not working properly."
        else 
          # wait 60 seconds to delete resources
          sleep 60s
        fi

        # delete operator's HelmRelease
        operator_charts=$(kubectl get hr -ndefault -ojsonpath={.items[*].metadata.name})
        log "INFO" "Deleting operator charts: $operator_charts"
        kubectl delete hr $operator_charts -ndefault
        if [[ $? =~ 1 ]]; then
          log "ERROR" "kubectl delete not working properly."
        fi

        log "INFO" "HelmReleases are successfully deleted!"
