apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: openstack-infra-
  namespace: argo
spec:
  entrypoint: deploy
  serviceAccountName: argo-deploy-sa
  arguments:
    parameters:
    - name: app_name
      value: openstack
  templates:
  - name: deploy
    dag:
      tasks:
      - name: infra
        templateRef:
          name: deploy-helmrelease
          template: ChartGroup
        arguments:
          parameters: 
          - name: chart_list
            value: |
              [
                "ceph-provisioners",
                "ingress",
                "memcached",
                "rabbitmq",
                "mariadb"
              ]
        dependencies: []
