apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: openstack-infra
  namespace: argo
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: site_name
      value: "decapod-reference"
    - name: app_group
      value: "openstack"
    - name: manifest_repo_url
      value: "https://github.com/openinfradev/decapod-manifests"
    - name: revision
      value: main
  templates:
  - name: deploy
    dag:
      tasks:
      - name: operator
        templateRef:
          name: create-application
          template: installApps
        arguments:
          parameters: 
          - name: list
            value: |
              [
                { "path": "ceph-provisioners", "namespace": "openstack" },
                { "path": "ingress", "namespace": "openstack" },
                { "path": "memcached", "namespace": "openstack" },
                { "path": "rabbitmq", "namespace": "openstack" },
                { "path": "mariadb", "namespace": "openstack" }
              ]
        dependencies: []
