## Example workflow that calls delete-project template ##
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: remove-lma-federation
  namespace: argo
spec:
  entrypoint: process
  arguments:
    parameters:
    # Filter to filter argocd apps (E.g., "app=lma")
    - name: filter
      value: "app=lma"
  templates:
  - name: process
    steps:
    - - name: removeLMA
        templateRef:
          name: delete-apps
          template: DeleteAppsByLabel
        arguments:
          parameters: 
          - name: filter
            value: "{{ workflow.parameters.filter }}"
