apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-apps
  namespace: argo
spec:
  templates:
  - name: DeleteAppsByLabel
    inputs:
      parameters:
      - name: filter
    activeDeadlineSeconds: 900
    container:
      name: 'delete-apps'
      image: docker.io/sktdev/argocd:latest
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -c
      - |
        # log into Argo CD server
        ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
        --password $ARGO_PASSWORD

        app_list=$(./argocd app list -l $FILTER --output name)
        if [[ $? -eq 0 ]]; then
          echo "$app_list" | xargs argocd delete --cascade -y
        else
          echo "No such label: $FILTER"
          exit 1
        fi
      envFrom:
        - secretRef:
            name: "decapod-argocd-config"
      env:
        - name: FILTER
          value: "{{inputs.parameters.filter}}"
