apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: delete-project
  namespace: argo
spec:
  templates:
  - name: DeleteProject
    inputs:
      parameters:
      - name: project
      - name: filter
    activeDeadlineSeconds: 900
    container:
      name: 'deleteProject'
      image: docker.io/sktdev/argocd:latest
      imagePullPolicy: IfNotPresent
      command:
      - /bin/bash
      - -c
      - |
        # log into Argo CD server
        ./argocd login $ARGO_SERVER --plaintext --insecure --username $ARGO_USERNAME \
        --password $ARGO_PASSWORD

        # check if project already exists.
        ./argocd proj get $PROJECT
        if [[ $? -eq 0 ]]; then
          ./argocd app list -l $FILTER --output name | xargs argocd delete --cascade -y
        else
          echo "No such project: $PROJECT"
          exit 1
        fi
      envFrom:
        - secretRef:
            name: "decapod-argocd-config"
      env:
        - name: PROJECT
          value: "{{inputs.parameters.project}}"
        - name: FILTER
          value: "{{inputs.parameters.filter}}"
