---
# Service account for the cleanup job.
apiVersion: v1
kind: ServiceAccount
metadata:
  name: argo-deploy-sa
  namespace: default
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: argo-deploy-crb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-deploy-role
subjects:
- kind: ServiceAccount
  name: argo-deploy-sa
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: argo-deploy-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - namespaces
  verbs:
  - get
  - watch
  - patch
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - delete
- apiGroups:
  - helm.fluxcd.io
  resources:
  - helmreleases
  verbs:
  - create
  - get
  - delete
  - list
  - patch

