apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: lma-
  namespace: argo
spec:
  entrypoint: deploy
  arguments:
    parameters:
    - name: repository_url
      value: "https://github.com/openinfradev/decapod-site-cd"
    - name: argo_server
      value: "192.168.97.192:30080"
    - name: argo_username
      value: "admin"
    - name: argo_password
      value: "taco1130@"
    - name: site_name
      value: "hanu-deploy-apps"
  templates:
  - name: deploy
    dag:
      tasks:
      - name: operator
        templateRef:
          name: create-application
          template: AppGroup
        arguments:
          parameters: 
          - name: list
            value: |
              [
                "prometheus-operator"
              ]
        dependencies: []